name: Pull latest video

on:
  workflow_dispatch: 
  schedule:
    - cron: 00 12,00 * * *
  push:
    branches: [ "gh-pages" ]

jobs:
  fetch:
    environment: youtube-api
    runs-on: ubuntu-latest
    steps:
    - name: Pull latest video
      shell: bash
      run: curl "https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=UC4U1e34boXZ7cjYjqzf9osw&maxResults=10&order=date&type=video&key=${{ secrets.YOUTUBE_API_KEY }}"
