name: Trigger fetch
on:
  schedule:
    - cron: 0 * * * *
jobs:
  trigger:
    environment: youtube-api
    runs-on: ubuntu-latest
    steps:
      - name: Trigger fetch workflow
        run: |
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/fetch-latest-video.yml/dispatches \
            -d '{"ref":"gh-pages"}'
