name: Fetch Latest Video
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  push:
    branches: [ "gh-pages" ]
    
jobs:
  trigger:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Fetch Latest Video
        run: |
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/fetch-latest-video.yml/dispatches \
            -d '{"ref":"gh-pages"}'
